# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: defcda3728f4c0039f4ce39f69bfb7d69b4626a2179b35aebee8e23b22d84000f3bc8f83c4d1326b2ad643079db6edc7bfa65a237ac643da23335d230fb1d04e

test:
  secret_key_base: af329c27c89d2371b382cc35766733dc3d58a4669f1354d7e8fec73e31946ee2ffdbc3e7ab1b65241d1f75e2c659680c9706c82b4d93e6e48203ddeac4c6278d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
